using BBDownT.Core.Protobuf;
using Google.Protobuf;
using System.Text;
using static BBDownT.Core.Entity.Entity;
using static BBDownT.Core.Util.HTTPUtil;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.IO;
using static BBDownT.Core.Logger;

namespace BBDownT.Core.Util;

public static partial class SubUtil
{
    internal static bool HaveValidUrls(IEnumerable<Subtitle> subtitles)
    {
        return subtitles.All(subtitle => !string.IsNullOrEmpty(subtitle.url));
    }

    //https://i0.hdslb.com/bfs/subtitle/subtitle_lan.json
    public static (string, string) GetSubtitleCode(string key)
    {
        //zh-hans => zh-Hans
        if (NonCapsRegex().Match(key) is { Success: true } result)
        {
            var v = result.Value;
            key = key.Replace(v, v.ToUpper());
        }

        return key switch
        {
            "ai-Zh"             => ("chi", "中文（简体, AI识别）"),
            "ai-En"             => ("eng", "English(generated by ai)"),
            "zh-CN"             => ("chi", "中文（简体）"),
            "zh-HK"             => ("chi", "中文（香港繁體）"),
            "zh-Hans"           => ("chi", "中文（简体）"),
            "zh-TW"             => ("chi", "中文（台灣繁體）"),
            "zh-Hant"           => ("chi", "中文（繁體）"),
            "en-US"             => ("eng", "English(USA)"),
            "ja"                => ("jpn", "日本語"),
            "ko"                => ("kor", "한국어"),
            "zh-SG"             => ("chi", "中文（新加坡）"),
            "ab"                => ("abk", "Аҳәынҭқарра"),
            "aa"                => ("aar", "Qafár af"),
            "af"                => ("afr", "Afrikaans"),
            "sq"                => ("alb", "Gjuha shqipe"),
            "ase"               => ("ase", "American Sign Language"),
            "am"                => ("amh", "አማርኛ"),
            "arc"               => ("arc", "ܐܪܡܝܐ"),
            "hy"                => ("arm", "հայերեն"),
            "as"                => ("asm", "অসমীয়া"),
            "ay"                => ("aym", "Aymar aru"),
            "az"                => ("aze", "Azərbaycan"),
            "bn"                => ("ben", "বাংলা ভাষার"),
            "ba"                => ("bak", "Башҡорттеле"),
            "eu"                => ("baq", "Euskara"),
            "be"                => ("bel", "беларуская мова biełaruskaja mova"),
            "bh"                => ("bih", "Bihar"),
            "bi"                => ("bis", "Bislama"),
            "bs"                => ("bos", "босански"),
            "br"                => ("bre", "Breton"),
            "bg"                => ("bul", "български"),
            "yue"               => ("chi", "粵語"),
            "yue-HK"            => ("chi", "粵語（中國香港）"),
            "ca"                => ("cat", "català"),
            "chr"               => ("chr", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ"),
            "cho"               => ("cho", "Chahta'"),
            "co"                => ("cos", "lingua corsa"),
            "hr"                => ("hrv", "Hrvatska"),
            "cs"                => ("cze", "čeština"),
            "da"                => ("dan", "Dansk"),
            "nl"                => ("dut", "Nederlands"),
            "nl-BE"             => ("dut", "Nederlands(Belgisch)"),
            "nl-NL"             => ("dut", "Nederlands(Nederlands)"),
            "dz"                => ("dzo", "རྫོང་ཁ།"),
            "en"                => ("eng", "English"),
            "en-CA"             => ("eng", "English(Canada)"),
            "en-IE"             => ("eng", "English(Ireland)"),
            "en-GB"             => ("eng", "English(UK)"),
            "eo"                => ("epo", "Esperanto"),
            "et"                => ("est", "Eestlane"),
            "fo"                => ("fao", "føroyskt"),
            "fj"                => ("fij", "Vakaviti"),
            "fil"               => ("phi", "Pilipino"),
            "fi"                => ("fin", "Suomi"),
            "fr"                => ("fre", "Français"),
            "fr-BE"             => ("fre", "Français(Belgique)"),
            "fr-CA"             => ("fre", "Français(Canada)"),
            "fr-FR"             => ("fre", "Français(La France)"),
            "fr-CH"             => ("fre", "Français(Suisse)"),
            "ff"                => ("ful", "Fulani"),
            "gl"                => ("glg", "galego"),
            "ka"                => ("geo", "ქართული ენა"),
            "de"                => ("ger", "Deutsch"),
            "de-AT"             => ("ger", "Deutsch(Österreich)"),
            "de-DE"             => ("ger", "Deutsch(Deutschland)"),
            "de-CH"             => ("ger", "Deutsch(Schweiz)"),
            "el"                => ("gre", "Ελληνικά"),
            "kl"                => ("kal", "Kalaallisut"),
            "gn"                => ("grn", "avañe'ẽ"),
            "gu"                => ("guj", "ગુજરાતી"),
            "hak"               => ("hak", "Hak-kâ-fa"),
            "hak-TW"            => ("hak", "Hak-kâ-fa"),
            "ha"                => ("hau", "هَوُسَ"),
            "iw"                => ("heb", "שפה עברית"),
            "hi"                => ("hin", "हिन्दी"),
            "hi-Latn"           => ("hin", "हिंदी(फोनेटिक)"),
            "hu"                => ("hun", "Magyar"),
            "is"                => ("ice", "icelandic"),
            "ig"                => ("ibo", "Asụsụ Igbo"),
            "id"                => ("ind", "Indonesia"),
            "ia"                => ("ina", "Interlingua"),
            "iu"                => ("iku", "ᐃᓄᒃᑎᑐᑦ"),
            "ik"                => ("ipk", "Inupiat"),
            "ga"                => ("gle", "Gaeilge na hÉireann"),
            "it"                => ("ita", "Italiano"),
            "jv"                => ("jav", "ꦧꦱꦗꦮ"),
            "kn"                => ("kan", "ಕನ್ನಡ"),
            "ks"                => ("kas", "कॉशुर"),
            "kk"                => ("kaz", "Қазақ тілі"),
            "km"                => ("khm", "ភាសាខ្មែរ"),
            "rw"                => ("kin", "Ikinyarwanda"),
            "tlh"               => ("tlh", "tlhIngan Hol"),
            "ku"                => ("kur", "Kurdî"),
            "ky"                => ("kir", "кыргыз тили"),
            "lo"                => ("lao", "ພາສາລາວ"),
            "la"                => ("lat", "latīna"),
            "lv"                => ("lav", "latviešu valoda"),
            "ln"                => ("lin", "Lingála"),
            "lt"                => ("lit", "lietuvių kalba"),
            "lb"                => ("ltz", "Lëtzebuergesch"),
            "mk"                => ("mac", "Македонски јазик"),
            "mg"                => ("mlg", "maa.laa.gaas"),
            "ms"                => ("may", "Melayu"),
            "ml"                => ("mal", "മലയാളം"),
            "mt"                => ("mlt", "Lingwa Maltija"),
            "mi"                => ("mao", "Māori"),
            "mr"                => ("mar", "मराठी Marāṭhī"),
            "mas"               => ("mas", "Maasai"),
            "nan"               => ("nan", "閩南語"),
            "nan-TW"            => ("nan", "閩南語(台灣)"),
            "lus"               => ("lus", "Mizo ṭawng"),
            "mo"                => ("mol", "Limba moldovenească"),
            "mn"                => ("mon", "монгол хэл"),
            "my"                => ("bur", "မြန်မာဘာသာ"),
            "na"                => ("nau", "Dorerin Naoero"),
            "nv"                => ("nav", "Diné bizaad"),
            "ne"                => ("nep", "नेपाली Nepālī"),
            "no"                => ("nor", "norsk språk"),
            "fa"                => ("per", "فارسی"),
            "fa-AF"             => ("per", "فارسی"),
            "fa-IR"             => ("per", "فارسی"),
            "pl"                => ("pol", "Polski"),
            "pt"                => ("por", "Português"),
            "pt-BR"             => ("por", "Português(brasil)"),
            "pt-PT"             => ("por", "Português(portugal)"),
            "ro"                => ("rum", "Română"),
            "ru"                => ("rus", "Русский"),
            "ru-Latn"           => ("rus", "Русский(фонетический)"),
            "sr"                => ("srp", "Српски"),
            "sr-Cyrl"           => ("srp", "Српски(ћирилица)"),
            "sr-Latn"           => ("srp", "Српски(латиница)"),
            "sh"                => ("scr", "srpskohrvatski"),
            "sk"                => ("slo", "slovenský"),
            "es"                => ("spa", "Español"),
            "es-419"            => ("spa", "Español(Latinoamérica)"),
            "es-MX"             => ("spa", "Español(México)"),
            "es-ES"             => ("spa", "Español(España)"),
            "es-US"             => ("spa", "Español(Estados Unidos)"),
            "sv"                => ("swe", "Svenska"),
            "tl"                => ("tgl", "Tagalog"),
            "th"                => ("tha", "ไทย"),
            "tr"                => ("tur", "Türkçe"),
            "uk"                => ("ukr", "Українська"),
            "ur"                => ("urd", "Urdu"),
            "vi"                => ("vie", "Tiếng Việt"),
            //太多了，我蚌埠住了，后面懒得查
            //"ie"                => ("", ""),
            //"oc"                => ("",   ""),
            //"or"                => ("",   ""),
            //"om"                => ("",   ""),
            //"ps"                => ("",   ""),
            //"pa"                => ("",   ""),
            //"qu"                => ("",   ""),
            //"rm"                => ("",   ""),
            //"rn"                => ("",   ""),
            //"sm"                => ("",   ""),
            //"sg"                => ("",   ""),
            //"sa"                => ("",   ""),
            //"gd"                => ("",   ""),
            //"sdp"               => ("",   ""),
            //"sn"                => ("",   ""),
            //"scn"               => ("",   ""),
            //"sd"                => ("",   ""),
            //"si"                => ("",   ""),
            //"sl"                => ("",   ""),
            //"so"                => ("",   ""),
            //"st"                => ("",   ""),
            //"su"                => ("",   ""),
            //"sw"                => ("",   ""),
            //"ss"                => ("",   ""),
            //"tg"                => ("",   ""),
            //"ta"                => ("",   ""),
            //"tt"                => ("",   ""),
            //"te"                => ("",   ""),
            //"ti"                => ("",   ""),
            //"to"                => ("",   ""),
            //"ts"                => ("",   ""),
            //"tn"                => ("",   ""),
            //"tk"                => ("",   ""),
            //"tw"                => ("",   ""),
            //"uz"                => ("",   ""),
            //"vo"                => ("",   ""),
            //"cy"                => ("",   ""),
            //"fy"                => ("",   ""),
            //"wo"                => ("",   ""),
            //"xh"                => ("",   ""),
            //"yi"                => ("",   ""),
            //"yo"                => ("",   ""),
            //"zu"                => ("",   ""),
            _ => ("und", "Undetermined")
        };
    }

    #region 字幕接口

    private static async Task<List<Subtitle>?> GetIntlSubtitlesFromApi1Async(string aid, string cid, string epId, int index)
    {
        try
        {
            List<Subtitle> subtitles = new();
            string api = "https://" + (Config.EPHOST == "api.bilibili.com" ? "api.biliintl.com" : Config.EPHOST) + $"/intl/gateway/web/v2/subtitle?episode_id={epId}";
            string json = await GetSubtitleWebTextAsync(api);
            using var infoJson = JsonDocument.Parse(json);
            var subs = infoJson.RootElement.GetProperty("data").GetProperty("subtitles").EnumerateArray();
            foreach (var sub in subs)
            {
                var lan = sub.GetProperty("lang_key").ToString();
                var url = sub.GetProperty("url").ToString();
                Subtitle subtitle = new()
                {
                    url = url,
                    lan = lan,
                    path = $"{PathSegmentSanitizer.Sanitize(aid)}/{PathSegmentSanitizer.Sanitize(aid)}.{PathSegmentSanitizer.Sanitize(cid)}.{PathSegmentSanitizer.Sanitize(lan)}{(url.Contains(".json") ? ".srt" : ".ass")}"
                };

                subtitles.Add(subtitle);

            }
            return subtitles;
        }
        catch (Exception ex)
        {
            LogDebug("国际字幕接口1失败: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetIntlSubtitlesFromApi2Async(string aid, string cid, string epId, int index)
    {
        try
        {
            List<Subtitle> subtitles = new();
            string api = "https://" + (Config.HOST == "api.bilibili.com" ? "api.bilibili.tv" : Config.HOST) +
                         $"/intl/gateway/v2/ogv/view/app/season?ep_id={epId}&platform=android&s_locale=zh_SG" + (Config.TOKEN != "" ? $"&access_key={Config.TOKEN}" : "");
            string json = await GetSubtitleWebTextAsync(api);
            using var infoJson = JsonDocument.Parse(json);
            var subs = infoJson.RootElement.GetProperty("result").GetProperty("modules")[0].GetProperty("data")
                .GetProperty("episodes")[index - 1].GetProperty("subtitles").EnumerateArray();
            foreach (var sub in subs)
            {
                var lan = sub.GetProperty("key").ToString();
                var url = sub.GetProperty("url").ToString().Replace("\\\\/", "/");
                Subtitle subtitle = new()
                {
                    url = url,
                    lan = lan,
                    path = $"{PathSegmentSanitizer.Sanitize(aid)}/{PathSegmentSanitizer.Sanitize(aid)}.{PathSegmentSanitizer.Sanitize(cid)}.{PathSegmentSanitizer.Sanitize(lan)}{(url.Contains(".json") ? ".srt" : ".ass")}"
                };

                subtitles.Add(subtitle);

            }
            return subtitles;
        }
        catch (Exception ex)
        {
            LogDebug("国际字幕接口2失败: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromApi1Async(string aid, string cid, string epId, int index)
    {
        try
        {
            string api = $"https://api.bilibili.com/x/web-interface/view?aid={aid}&cid={cid}";
            return ParseJsonSubtitles(await GetSubtitleWebTextAsync(api), "list", cid);
        }
        catch (Exception ex)
        {
            LogDebug("字幕接口1失败: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromApi2Async(string aid, string cid, string epId, int index)
    {
        try
        {
            string api = $"https://api.bilibili.com/x/player/wbi/v2?cid={cid}&aid={aid}";
            return ParseJsonSubtitles(await GetSubtitleWebTextAsync(api), "subtitles");
        }
        catch (Exception ex)
        {
            LogDebug("字幕接口2失败: {0}", ex.Message);
            return null;
        }
    }

    private static byte[] GetPayload(long aid, long cid)
    {
        var obj = new DmViewReq
        {
            Pid = aid,
            Oid = cid,
            Type = 1,
            Spmid = "main.ugc-video-detail.0.0",
        };
        return AppHelper.PackMessage(obj.ToByteArray());
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromApi3Async(string aid, string cid, string epId, int index)
    {
        try
        {
            //grpc调用接口 protobuf
            string api = "https://app.biliapi.net/bilibili.community.service.dm.v1.DM/DmView";

            var data = GetPayload(Convert.ToInt64(aid), Convert.ToInt64(cid));

            var t = AppHelper.ReadMessage(await GetPostResponseAsync(api, data));
            var resp = new MessageParser<DmViewReply>(() => new DmViewReply()).ParseFrom(t);

            return MapProtoSubtitles(resp.Subtitle);
        }
        catch (Exception ex)
        {
            LogDebug("字幕接口3失败: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromWebApiAsync(string aid, string cid)
    {
        string contextExt = Uri.EscapeDataString("{\"video_type\":1}");
        string api = $"https://api.bilibili.com/x/v2/subtitle/web/view?oid={Uri.EscapeDataString(cid)}&pid={Uri.EscapeDataString(aid)}" +
                     $"&context_ext={contextExt}&type=1&cur_production_type=0&preferred_language=ai-zh&playlist_switch=0";
        try
        {
            using var request = new HttpRequestMessage(HttpMethod.Get, api);
            request.Headers.TryAddWithoutValidation("User-Agent", UserAgent);
            request.Headers.TryAddWithoutValidation("Referer", "https://www.bilibili.com/");
            request.Headers.TryAddWithoutValidation("Accept", "application/octet-stream");
            TryAddCookieHeader(request, api);
            using var response = (await AppHttpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead)).EnsureSuccessStatusCode();
            return ParseSubtitleWebResponse(await response.Content.ReadAsByteArrayAsync());
        }
        catch (Exception ex)
        {
            LogDebug("新版字幕接口失败: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<string> GetSubtitleWebTextAsync(string api)
    {
        using var request = new HttpRequestMessage(HttpMethod.Get, api);
        request.Headers.TryAddWithoutValidation("User-Agent", UserAgent);
        request.Headers.TryAddWithoutValidation("Referer", "https://www.bilibili.com/");
        request.Headers.TryAddWithoutValidation("Accept", "application/json");
        TryAddCookieHeader(request, api);
        using var response = (await AppHttpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead)).EnsureSuccessStatusCode();
        return await response.Content.ReadAsStringAsync();
    }

    internal static List<Subtitle> ParseSubtitleWebResponse(ReadOnlySpan<byte> payload)
    {
        var reply = new MessageParser<SubtitleWebReply>(() => new SubtitleWebReply()).ParseFrom(payload.ToArray());
        return MapProtoSubtitles(reply.Subtitle);
    }

    internal static List<Subtitle> MergeSubtitleSources(IEnumerable<IEnumerable<Subtitle>?> sources, string aid, string cid)
    {
        var result = new List<Subtitle>();
        var seenIds = new HashSet<string>(StringComparer.Ordinal);
        var seenUrls = new HashSet<string>(StringComparer.Ordinal);
        foreach (var source in sources)
        {
            if (source == null)
                continue;
            foreach (var subtitle in source)
            {
                subtitle.url = NormalizeSubtitleUrl(subtitle.url);
                if (!IsUsableSubtitle(subtitle))
                    continue;
                bool duplicateId = !string.IsNullOrEmpty(subtitle.id) && seenIds.Contains(subtitle.id);
                bool duplicateUrl = seenUrls.Contains(subtitle.url);
                if (duplicateId || duplicateUrl)
                {
                    continue;
                }
                if (!string.IsNullOrEmpty(subtitle.id))
                    seenIds.Add(subtitle.id);
                seenUrls.Add(subtitle.url);
                result.Add(subtitle);
            }
        }
        AssignSubtitlePaths(result, aid, cid);
        return result;
    }

    internal static List<Subtitle> ParseJsonSubtitles(string json, string tracksProperty, string? expectedCid = null)
    {
        using var infoJson = JsonDocument.Parse(json);
        var data = infoJson.RootElement.GetProperty("data");
        // The legacy view endpoint can return the first page despite a different cid query.
        if (expectedCid is not null && GetJsonString(data, "cid") != expectedCid) return [];
        if (data.TryGetProperty("need_login_subtitle", out var login) && login.ValueKind == JsonValueKind.True)
            LogWarn("播放器字幕接口要求登录，将尝试其他字幕来源。");
        var subtitle = data.GetProperty("subtitle");
        var result = new List<Subtitle>();
        foreach (var sub in subtitle.GetProperty(tracksProperty).EnumerateArray())
        {
            result.Add(new Subtitle
            {
                id = GetJsonString(sub, "id") ?? GetJsonString(sub, "id_str"),
                lan = GetJsonString(sub, "lan") ?? GetJsonString(sub, "lang_key") ?? GetJsonString(sub, "key") ?? "",
                lanDoc = GetJsonString(sub, "lan_doc") ?? GetJsonString(sub, "lanDoc"),
                type = GetJsonInt(sub, "type"),
                aiType = GetJsonInt(sub, "ai_type") ?? GetJsonInt(sub, "aiType"),
                url = GetJsonString(sub, "subtitle_url") ?? GetJsonString(sub, "subtitleUrl") ?? "",
                path = ""
            });
        }
        return result;
    }

    private static List<Subtitle> MapProtoSubtitles(VideoSubtitle? videoSubtitle)
    {
        if (videoSubtitle == null)
            return [];
        return videoSubtitle.Subtitles.Select(item => new Subtitle
        {
            id = item.HasId ? item.Id.ToString() : (item.HasIdStr ? item.IdStr : null),
            lan = item.Lan,
            lanDoc = item.HasLanDoc ? item.LanDoc : (item.HasLanDocBrief ? item.LanDocBrief : null),
            type = item.Type,
            aiType = item.HasAiType ? item.AiType : null,
            url = item.SubtitleUrl,
            path = ""
        }).ToList();
    }

    private static string? GetJsonString(JsonElement value, string property)
    {
        return value.TryGetProperty(property, out var element) && element.ValueKind != JsonValueKind.Null ? element.ToString() : null;
    }

    private static int? GetJsonInt(JsonElement value, string property)
    {
        if (!value.TryGetProperty(property, out var element) || element.ValueKind == JsonValueKind.Null)
            return null;
        if (element.ValueKind == JsonValueKind.Number && element.TryGetInt32(out var number))
            return number;
        return element.ValueKind == JsonValueKind.String && int.TryParse(element.GetString(), out var textNumber) ? textNumber : null;
    }

    private static string NormalizeSubtitleUrl(string url)
    {
        url = url.Trim();
        return url.StartsWith("//", StringComparison.Ordinal) ? "https:" + url : url;
    }

    private static bool HasUsableSubtitle(IEnumerable<Subtitle>? subtitles)
    {
        return subtitles?.Any(IsUsableSubtitle) == true;
    }

    private static bool IsUsableSubtitle(Subtitle subtitle) => !string.IsNullOrWhiteSpace(subtitle.lan)
        && Uri.TryCreate(NormalizeSubtitleUrl(subtitle.url), UriKind.Absolute, out var uri)
        && uri.Scheme is "http" or "https";

    private static void AssignSubtitlePaths(IList<Subtitle> subtitles, string aid, string cid)
    {
        string prefix = $"{PathSegmentSanitizer.Sanitize(aid)}/{PathSegmentSanitizer.Sanitize(aid)}.{PathSegmentSanitizer.Sanitize(cid)}";
        var usedPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var group in subtitles.GroupBy(subtitle => PathSegmentSanitizer.Sanitize(subtitle.lan), StringComparer.OrdinalIgnoreCase))
        {
            var items = group.ToList();
            for (int i = 0; i < items.Count; i++)
            {
                string extension = Path.GetExtension(items[i].path);
                if (extension is not ".srt" and not ".ass")
                    extension = ".srt";
                string? id = items[i].id;
                string suffix = items.Count == 1 ? "" : "." + (string.IsNullOrEmpty(id) ? (i + 1).ToString() : PathSegmentSanitizer.Sanitize(id));
                string stem = $"{prefix}.{PathSegmentSanitizer.Sanitize(items[i].lan)}{suffix}";
                string path = stem + extension;
                for (int n = 2; !usedPaths.Add(path); n++) path = $"{stem}.{n}{extension}";
                items[i].path = path;
            }
        }
    }

    #endregion

    public static async Task<List<Subtitle>> GetSubtitlesAsync(string aid, string cid, string epId, int index, bool intl)
    {
        if (intl)
        {
            var firstIntl = await GetIntlSubtitlesFromApi1Async(aid, cid, epId, index);
            var intlSources = new List<List<Subtitle>?>
            {
                firstIntl
            };
            if (!HasUsableSubtitle(firstIntl))
                intlSources.Add(await GetIntlSubtitlesFromApi2Async(aid, cid, epId, index));
            return MergeSubtitleSources(intlSources, aid, cid);
        }

        var sources = new List<List<Subtitle>?>();
        var webSubtitles = await GetSubtitlesFromWebApiAsync(aid, cid);
        sources.Add(webSubtitles);

        // Logged-in web sources supplement the new endpoint. Without a cookie,
        // legacy web sources are only needed when the preferred source is empty.
        if (!string.IsNullOrEmpty(Config.COOKIE) || !HasUsableSubtitle(webSubtitles))
        {
            sources.Add(await GetSubtitlesFromApi2Async(aid, cid, epId, index));
        }

        var subtitles = MergeSubtitleSources(sources, aid, cid);
        if (subtitles.Count == 0)
        {
            sources.Add(await GetSubtitlesFromApi1Async(aid, cid, epId, index));
            subtitles = MergeSubtitleSources(sources, aid, cid);
        }
        if (subtitles.Count == 0)
        {
            sources.Add(await GetSubtitlesFromApi3Async(aid, cid, epId, index));
            subtitles = MergeSubtitleSources(sources, aid, cid);
        }

        if (subtitles.Count == 0)
        {
            bool allFailed = sources.All(source => source == null);
            LogWarn(allFailed ? "字幕来源请求全部失败" : "未找到可用字幕，可能需要登录或该视频没有字幕");
        }

        return subtitles;
    }

    public static async Task SaveSubtitleAsync(string url, string path)
    {
        if (path.EndsWith(".srt"))
            await File.WriteAllTextAsync(path, ConvertSubFromJson(await GetSubtitleWebTextAsync(url)), Encoding.UTF8);
        else
            await File.WriteAllTextAsync(path, await GetSubtitleWebTextAsync(url), Encoding.UTF8);
    }

    private static string ConvertSubFromJson(string jsonString)
    {
        StringBuilder lines = new();
        var json = JsonDocument.Parse(jsonString);
        var sub = json.RootElement.GetProperty("body").EnumerateArray().ToList();
        for(int i = 0; i < sub.Count; i++)
        {
            var line = sub[i];
            lines.AppendLine((i + 1).ToString());
            if (line.TryGetProperty("from", out JsonElement from))
            {
                lines.AppendLine($"{FormatTime(from.GetDouble())} --> {FormatTime(line.GetProperty("to").GetDouble())}");
            }
            else
            {
                lines.AppendLine($"{FormatTime(0.0)} --> {FormatTime(line.GetProperty("to").GetDouble())}");
            }
            //有的没有内容
            if (line.TryGetProperty("content", out JsonElement content))
                lines.AppendLine(content.ToString());
            lines.AppendLine();
        }
        return lines.ToString();
    }

    private static string FormatTime(double sec) //64.13
    {
        return TimeSpan.FromSeconds(sec).ToString(@"hh\:mm\:ss\,fff");
    }

    [GeneratedRegex("-[a-z]")]
    private static partial Regex NonCapsRegex();
}
